name: Update Avrae Collections
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: modified-files
      uses: jitterbit/get-changed-files@master
      with:
        format: 'json'
    - uses: ianfhunter/avrae-autoupdate@patch-2
      with:
        avrae-token: '${{ secrets.AVRAE_TOKEN }}'
        collections_id_file_name: 'collections.json'
        gvars_id_file_name: 'gvars.json'
        modified-files: '${{ steps.modified-files.outputs.added_modified }}'
        collection-ids-file: 'collections.json'
